schema_version: 2
upstream:
  repository: https://github.com/ds-wizard/wizard-locales.git
  locale: zh_Hant
versions:
  v4.29:
    upstream_ref: v4.29
    state: maintenance
  v4.30:
    upstream_ref: v4.30
    state: maintenance
  v4.31:
    upstream_ref: v4.31
    state: maintenance
  v4.32:
    upstream_ref: v4.32
    state: maintenance
  v4.33:
    upstream_ref: v4.33
    state: maintenance
  v4.34:
    upstream_ref: v4.34
    state: active
